DATA_TYPES = [
    ('text', 'Text'),
    ('textarea', 'TextArea'),
    ('date', 'Date'),
    ('geo', 'Geolocation'),
    ('number', 'Number'),
    ('image', 'Image'),
    ('video', 'Video'),
    ('audio', 'Audio'),
    ('file', 'File'),
    # ('link', 'Link'),
    # ('list', 'List'),
    # ('checkbox', 'Checkbox'),
    # ('radio', 'Radio'),
    # ('dropdown', 'Dropdown'),
    # ('rating', 'Rating'),
    # ('slider', 'Slider'),
    # ('range', 'Range'),
    # ('color', 'Color'),
    # ('email', 'Email'),
    # ('phone', 'Phone'),
    # ('password', 'Password'),
    # ('datetime', 'Datetime'),
    # ('time', 'Time'),
    # ('url', 'URL'),
    # ('html', 'HTML'),
    # ('markdown', 'Markdown'),
    # ('json', 'JSON'),
    # ('xml', 'XML'),
    # ('yaml', 'YAML'),
    # ('csv', 'CSV'),
    # ('excel', 'Excel'),
    # ('pdf', 'PDF'),
    # ('word', 'Word'),
    # ('powerpoint', 'PowerPoint'),
    # ('code', 'Code'),
    # ('formula', 'Formula'),
    # ('math', 'Math'),
    # ('currency', 'Currency'),
    # ('percent', 'Percent'),
    # ('unit', 'Unit'),
    # ('duration', 'Duration'),
    # ('timezone', 'Timezone'),
    # ('language', 'Language'),
    # ('country', 'Country'),
    # ('currency', 'Currency'),
    # ('emoji', 'Emoji'),
    # ('flag', 'Flag'),
]