# Generated by Django 4.2.11 on 2024-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='isPublic',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='reputationRating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_bio',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
